version: '2'

services:

  spark-master:
    image: sstirlin/spark-master:2.4.0-hadoop2.7_v2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: sstirlin/spark-worker:2.4.0-hadoop2.7_v2
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
        
#  resourcemanager:
#    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
#    container_name: resourcemanager
#    hostname: resourcemanager
#    depends_on:
#      - namenode
#      - datanode1
#      - datanode2
#    env_file:
#      - ./hadoop.env
# 
#  historyserver:
#    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
#    container_name: historyserver
#    hostname: historyserver
#    depends_on:
#      - namenode
#      - datanode1
#      - datanode2
#    volumes:
#      - hadoop_historyserver:/hadoop/yarn/timeline
#    env_file:
#      - ./hadoop.env
# 
#  nodemanager1:
#    image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
#    container_name: nodemanager1
#    hostname: nodemanager1
#    depends_on:
#      - namenode
#      - datanode1
#      - datanode2
#    env_file:
#      - ./hadoop.env
        
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode1
    hostname: datanode1
    ports:
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
#  datanode2:
#    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
#    container_name: datanode2
#    hostname: datanode2
#    depends_on:
#      - namenode
#    volumes:
#      - hadoop_datanode2:/hadoop/dfs/data
#    env_file:
#      - ./hadoop.env
#  
#  datanode3:
#    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
#    container_name: datanode3
#    hostname: datanode3
#    depends_on:
#      - namenode
#    volumes:
#      - hadoop_datanode3:/hadoop/dfs/data
#    env_file:
#      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
#  hadoop_datanode2:
#  hadoop_datanode3:
#  hadoop_historyserver:
